using Analogy.Interfaces;
using System;
using System.Collections.Generic;

namespace Analogy
{
    public static class CommonChangeLog
    {
        public static IEnumerable<AnalogyChangeLog> GetChangeLog()
        {
            return new List<AnalogyChangeLog>
            {
                new AnalogyChangeLog("Add ability to add notes to log messages. #217 ",AnalogChangeLogType.Improvement,"Lior Banai",new DateTime(2020,07,10)),
                new AnalogyChangeLog("Shows AnalogyLogMessage's AdditionalInformation Properties in Detailed Window. #215",AnalogChangeLogType.Improvement,"Lior Banai",new DateTime(2020,07,10)),
                new AnalogyChangeLog("System.ArgumentException when using the 'messages grouping' tab with a log file that contains custom columns. #225",AnalogChangeLogType.Bug,"Lior Banai",new DateTime(2020,07,10)),
                new AnalogyChangeLog("Add providers icon to the ribbon page. #219",AnalogChangeLogType.Improvement,"Lior Banai",new DateTime(2020,07,09)),
                new AnalogyChangeLog("Main log viewer window always starts up full screen. #213",AnalogChangeLogType.Improvement,"Lior Banai",new DateTime(2020,07,05)),
                new AnalogyChangeLog("Cleanup Filtering UI Elements. #212",AnalogChangeLogType.Improvement,"Lior Banai",new DateTime(2020,07,04)),
                new AnalogyChangeLog( "Add option to select rows and perform operation on the selection (save to file, open in new window, etc). #201",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 07, 03)),
                new AnalogyChangeLog( "Add dynamic columns at run time based on AdditionalInformation Property of AnalogyLogMessage. #206",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 07, 02)),
                new AnalogyChangeLog( "Add multi select of rows. #204",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 06, 28)),
                new AnalogyChangeLog( "Enable version check on startup. #200",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 06, 26)),
                new AnalogyChangeLog( "Ribbon Icons are not correct for real time data sources. #199",AnalogChangeLogType.Bug,"Lior Banai", new DateTime(2020, 06, 26)),
                new AnalogyChangeLog("[Windows Events log Parser] Unable to load system log files (*.evtx). #197",AnalogChangeLogType.Bug,"Lior Banai", new DateTime(2020, 06, 21)),
                new AnalogyChangeLog("Add MachineName to UI columns. #196",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 06, 20)),
                new AnalogyChangeLog("Add Recent Folder to The Ribbon UI. #193",AnalogChangeLogType.Feature,"Lior Banai", new DateTime(2020, 06, 19)),
                new AnalogyChangeLog("Remember Last X open folders locations in the Open folder UI. #183",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 06, 19)),
                new AnalogyChangeLog("Duplicate files are listed in the UI. #192",AnalogChangeLogType.Bug,"Lior Banai", new DateTime(2020, 06, 19)),
                new AnalogyChangeLog("NullReferenceException when using the data visualizer on a Serilog/Clef log file #189",AnalogChangeLogType.Bug,"Lior Banai", new DateTime(2020, 06, 18)),
                new AnalogyChangeLog("Upgrade to DevExpress 19.1.11. #187",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 06, 11)),
                new AnalogyChangeLog("Reload file is ignore when caching is on #181",AnalogChangeLogType.Bug,"Lior Banai", new DateTime(2020, 06, 04)),
                new AnalogyChangeLog("Log Analysis: Add free-text pie chart #177",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 05, 29)),
                new AnalogyChangeLog("Store date sorting order between runs #178",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 05, 29)),
                new AnalogyChangeLog("Allows application to minimized to the tray bar instead of closing #174",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 05, 28)),
                new AnalogyChangeLog("Add Cache cleaner #175",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 05, 28)),
                new AnalogyChangeLog("On reload of files add option to color mark the new messages #170",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 05, 28)),
                new AnalogyChangeLog("Add auto update/version checker #165",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 05, 22)),
                new AnalogyChangeLog("combine opened logs into one. #152",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 05, 22)),
            new AnalogyChangeLog("Add Reload option for loaded logs files #169",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 05, 14)),
            new AnalogyChangeLog("Add Columns extension support #149",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 05, 09)),
            new AnalogyChangeLog("Add an option to display date/time in local pattern #154",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 05, 09)),
            new AnalogyChangeLog("User settings: Allow user to change grid headers/titles #153",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 05, 08)),
            new AnalogyChangeLog("UI: Add alternate icons (light/dark themes) #167",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 05, 08)),
            new AnalogyChangeLog("Allow each Data provider to supply its own icons and Images for the UI #127",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 05, 02)),
            new AnalogyChangeLog("Open new logs as new tabs in the same application instance #155",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 04, 25)),
            new AnalogyChangeLog("Add Single Instance User settings #157",AnalogChangeLogType.Improvement,"Lior Banai", new DateTime(2020, 04, 25)),
            new AnalogyChangeLog("Date Time value is displayed wrong in Detailed Message window (Issue #156)", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2020, 04, 25)),
            new AnalogyChangeLog("Logs Analysis: add some pie charts (Issue #131)", AnalogChangeLogType.Feature, "Lior Banai", new DateTime(2020, 04, 06)),
            new AnalogyChangeLog("Logs Analysis: add log level distribution chart (Issue #129)", AnalogChangeLogType.Feature, "Lior Banai", new DateTime(2020, 04, 06)),
            new AnalogyChangeLog("Upgrade to DevExpress 19.1.10 (Issue #128)", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2020, 04, 06)),
            new AnalogyChangeLog("Bug: Dedicated user setting window does not call the Save method of the data provider (Issue #124", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2020, 04, 03)),
            new AnalogyChangeLog("Refactor interfaces (Issue #12 at https://github.com/Analogy-LogViewer/Analogy.Interfaces)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2020, 03, 31)),
            new AnalogyChangeLog("UI: Add button to open custom user setting window (Issue #113)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2020, 03, 15)),
            new AnalogyChangeLog("Add MessagePack binary format to built in supported Analogy Formats (Issue #102)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2020, 02, 29)),
            new AnalogyChangeLog("Add shortcut for toggle detailed messages info (Issue #96)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2020, 02, 14)),
            new AnalogyChangeLog("Upgrade DevExpress to v19.1.9 (Issue #97)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2020, 02, 14)),
            new AnalogyChangeLog("NullReferenceException during row painting (Philips ICAP data provider). (Issue #85)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 12, 27)),
            new AnalogyChangeLog("Persist Analogy internal log to file (issue #83)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2020, 01, 14)),
            new AnalogyChangeLog("Move to SDK-Style projects and package references. (issue #82)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 12, 27)),
            new AnalogyChangeLog("Upgrade DevExpress Version to 19.1.8 (Latest supported with current license)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 12, 27)),
            new AnalogyChangeLog("Default user setting are invalid for some properties (issue #76)", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2020, 01, 03)),
            new AnalogyChangeLog("Auto complete user setting is not working (issue #78)", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2019, 12, 27)),
            new AnalogyChangeLog("Add docking/un-docking management when more than one log is opened (issue #75)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 12, 24)),
            new AnalogyChangeLog("Changes in 'include Text' text box effect 'highlight lines...' text box (Issue #74)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 12, 20)),
            new AnalogyChangeLog("Add alert messages and notifications (Issue #46)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 12, 14)),
            new AnalogyChangeLog("Update all dependencies nuget versions (issue #73)", AnalogChangeLogType.None, "Lior Banai", new DateTime(2019, 12, 14)),
            new AnalogyChangeLog("Shortcuts keys are not correct (issue #72)", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2019, 12, 14)),
            new AnalogyChangeLog("Search filtering: Add user predefined search queries (issue #11)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 12, 13)),
            new AnalogyChangeLog("Add individual colors rules (issue #03)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 12, 12)),
            new AnalogyChangeLog("File listing should be sorted from newest to oldest and customizable by the user (issue #69)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 12, 09)),
            new AnalogyChangeLog("Consolidate all data providers (per factory) under the ribbon UI (issue #63)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 12, 09)),
            new AnalogyChangeLog("changing log level checks include text & Exclude text boxes (issue #68)", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2019, 12, 08)),
            new AnalogyChangeLog("Performance: Improve performance when querying messages for count display (issue #67)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 12, 07)),
            new AnalogyChangeLog("Add an option to remember last opened data provider (issue #65)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 12, 03)),
            new AnalogyChangeLog("Add logging of errors during startup for better debugging (issue #66)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 12, 03)),
            new AnalogyChangeLog("Add Date/time option to filter the messages (issue #62)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 11, 29)),
            new AnalogyChangeLog("Add export/import settings (issue #47)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 11, 23)),
            new AnalogyChangeLog("Add default file-data provider associations (issue #45)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 11, 23)),
            new AnalogyChangeLog("Allows disabling of data providers (issue #60)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 11, 22)),
            new AnalogyChangeLog("User Settings: Add Export/Import of messages' color settings (Issue #56)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 11, 19)),
            new AnalogyChangeLog("Bookmarks window is not customizable (font size). (issue #59)", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2019, 11, 19)),
            new AnalogyChangeLog("Detailed message window is ignoring in-place filtering (in the grid control) and shows incorrect number of messages (issue #58)", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2019, 11, 19)),
            new AnalogyChangeLog("Usability: add indication in the file list of the loaded file. (Issue #57))", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 11, 19)),
            new AnalogyChangeLog("user settings: Add option to set default date sort option (ascend/descend) (issue #55)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 11, 17)),
            new AnalogyChangeLog("File Pooling: add indication of number of new messages per update (issue #51)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 11, 14)),
            new AnalogyChangeLog("File Pooling: Add an option to ignore global caching settings or adding to recent files history. (issue #54)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 11, 14)),
            new AnalogyChangeLog("NLog Data Provider: Add import/export of settings. (issue #52)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 11, 12)),
            new AnalogyChangeLog("Built-in Data providers are ignored when double clicking and log file. (issue #50)", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2019, 11, 10)),
            new AnalogyChangeLog("File pooling: duplicate entries are added (issue #49)", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2019, 11, 10)),
            new AnalogyChangeLog("Coloring: Add user settings for log level colors (issue #48)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 11, 09)),
            new AnalogyChangeLog("Data Providers: Add NLog data Provider (issue #19)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 11, 07)),
            new AnalogyChangeLog("Performance: Load data providers asynchronously during startup (issue #40)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 10, 21)),
            new AnalogyChangeLog("adding .net Core 3.0 Target", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 10, 26)),
            new AnalogyChangeLog("Offline files: Add option for file pooling. (issue #36)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 10, 24)),
            new AnalogyChangeLog("cleanup old namespaces (issue #34)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 10, 18)),
            new AnalogyChangeLog("frameworks update: interface dll is not target .net standard 2.0 and Analogy UI is .net framework 4.7.2 (issues #32,#33)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 10, 18)),
            new AnalogyChangeLog("UI: not all UI elements support themes (issue #28)", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2019, 10, 14)),
            new AnalogyChangeLog("UI: Add an option (user setting) to auto scroll to last message (Issue #26)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 10, 13)),
            new AnalogyChangeLog("Fix: DevExpress Control: Sometimes an error occurs and the grid displays a big red X (Issue #4)", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2019, 10, 11)),
            new AnalogyChangeLog("UI: Add fast file caching switching (Issue #23)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 10, 11)),
            new AnalogyChangeLog("UI: Add more information about messages in the Message's detail window (Issue #22)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 10, 09)),
            new AnalogyChangeLog("Fix: Online Data Providers are not disposed during shutdown of Analogy (Issue #21)", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2019, 10, 09)),
            new AnalogyChangeLog("Fix: Folder loading is ignoring data source supported files (Issue #18)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 09, 26)),
            new AnalogyChangeLog("Add an option to un-dock current view and keep receiving new messages (Issue #16)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 09, 25)),
            new AnalogyChangeLog("duplicate chrome tab behavior (close tab keyboard shortcut, close all other tabs, etc) (Issue #8)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 09, 24)),
            new AnalogyChangeLog("remove Auto Start value form the interface and make it UI option", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 09, 21)),
            new AnalogyChangeLog("Startup data sources: add a user setting to define list of startup data sources (Issue #10)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 09, 21)),
            new AnalogyChangeLog("Windows Event logs: add support for custom logs in addition to Windows logs (Issue #7)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 09, 20)),
            new AnalogyChangeLog("user settings are not saved between different versions (Issue #13)", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2019, 09, 20)),
            new AnalogyChangeLog("Add resource usage indication and idle mode (Issue #6)", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 09, 20)),
            new AnalogyChangeLog("Fix unable to save logs for real time Data sources", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2019, 09, 09)),
            new AnalogyChangeLog("Add more information in the offline files listing.", AnalogChangeLogType.Improvement, "Lior Banai", new DateTime(2019, 08, 31)),
            new AnalogyChangeLog("Fix about Page loading.", AnalogChangeLogType.Bug, "Lior Banai", new DateTime(2019, 08, 30)),
            new AnalogyChangeLog("First release as open source tool.", AnalogChangeLogType.Feature, "Lior Banai", new DateTime(2019, 08, 19)),
            };
        }
    }
}
