//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analogy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModuleText {
            get {
                return ((string)(this["ModuleText"]));
            }
            set {
                this["ModuleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SourceText {
            get {
                return ((string)(this["SourceText"]));
            }
            set {
                this["SourceText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHistoryClearedMessages {
            get {
                return ((bool)(this["ShowHistoryClearedMessages"]));
            }
            set {
                this["ShowHistoryClearedMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveSearchFilters {
            get {
                return ((bool)(this["SaveSearchFilters"]));
            }
            set {
                this["SaveSearchFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentFiles {
            get {
                return ((string)(this["RecentFiles"]));
            }
            set {
                this["RecentFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RecentFilesCount {
            get {
                return ((int)(this["RecentFilesCount"]));
            }
            set {
                this["RecentFilesCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint OpenFilesCount {
            get {
                return ((uint)(this["OpenFilesCount"]));
            }
            set {
                this["OpenFilesCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan AnalogyRunningTime {
            get {
                return ((global::System.TimeSpan)(this["AnalogyRunningTime"]));
            }
            set {
                this["AnalogyRunningTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableUserStatistics {
            get {
                return ((bool)(this["EnableUserStatistics"]));
            }
            set {
                this["EnableUserStatistics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint AnalogyLaunchesCount {
            get {
                return ((uint)(this["AnalogyLaunchesCount"]));
            }
            set {
                this["AnalogyLaunchesCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DevExpress Style")]
        public string ApplicationSkinName {
            get {
                return ((string)(this["ApplicationSkinName"]));
            }
            set {
                this["ApplicationSkinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SimpleMode {
            get {
                return ((bool)(this["SimpleMode"]));
            }
            set {
                this["SimpleMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableFileCaching {
            get {
                return ((bool)(this["EnableFileCaching"]));
            }
            set {
                this["EnableFileCaching"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoadExtensionsOnStartup {
            get {
                return ((bool)(this["LoadExtensionsOnStartup"]));
            }
            set {
                this["LoadExtensionsOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StartupExtensions {
            get {
                return ((string)(this["StartupExtensions"]));
            }
            set {
                this["StartupExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartupRibbonMinimized {
            get {
                return ((bool)(this["StartupRibbonMinimized"]));
            }
            set {
                this["StartupRibbonMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartupErrorLogLevel {
            get {
                return ((bool)(this["StartupErrorLogLevel"]));
            }
            set {
                this["StartupErrorLogLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250000")]
        public int PagingSize {
            get {
                return ((int)(this["PagingSize"]));
            }
            set {
                this["PagingSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PagingEnabled {
            get {
                return ((bool)(this["PagingEnabled"]));
            }
            set {
                this["PagingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowChangeLogAtStartUp {
            get {
                return ((bool)(this["ShowChangeLogAtStartUp"]));
            }
            set {
                this["ShowChangeLogAtStartUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IncludeText {
            get {
                return ((string)(this["IncludeText"]));
            }
            set {
                this["IncludeText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchAlsoInSourceAndModule {
            get {
                return ((bool)(this["SearchAlsoInSourceAndModule"]));
            }
            set {
                this["SearchAlsoInSourceAndModule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IdleMode {
            get {
                return ((bool)(this["IdleMode"]));
            }
            set {
                this["IdleMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int IdleTimeMinutes {
            get {
                return ((int)(this["IdleTimeMinutes"]));
            }
            set {
                this["IdleTimeMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\"Application\",\"System\"]")]
        public string WindowsEventLogs {
            get {
                return ((string)(this["WindowsEventLogs"]));
            }
            set {
                this["WindowsEventLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoStartDataProviders {
            get {
                return ((string)(this["AutoStartDataProviders"]));
            }
            set {
                this["AutoStartDataProviders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoScrollToLastMessage {
            get {
                return ((bool)(this["AutoScrollToLastMessage"]));
            }
            set {
                this["AutoScrollToLastMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogParsersSettings {
            get {
                return ((string)(this["LogParsersSettings"]));
            }
            set {
                this["LogParsersSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColorSettings {
            get {
                return ((string)(this["ColorSettings"]));
            }
            set {
                this["ColorSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultDescendOrder {
            get {
                return ((bool)(this["DefaultDescendOrder"]));
            }
            set {
                this["DefaultDescendOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FactoriesOrder {
            get {
                return ((string)(this["FactoriesOrder"]));
            }
            set {
                this["FactoriesOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"FactoryName\":\"Analogy Logs Formats\",\"FactoryId\":\"d3047f5d-cfeb-4a69-8f10-ae5f4" +
            "d3f2d04\",\"UserSettingFileAssociations\":[],\"Status\":1},{\"FactoryName\":\"Analogy Ex" +
            "amples\",\"FactoryId\":\"4b1ebc0f-64dd-44a1-bc27-79dbfc6384cc\",\"UserSettingFileAssoc" +
            "iations\":[],\"Status\":1},{\"FactoryName\":\"gRPC Receiver\",\"FactoryId\":\"9bd37cc2-daa" +
            "7-4d17-974c-01ef3f3c79ba\",\"UserSettingFileAssociations\":[],\"Status\":1},{\"Factory" +
            "Name\":\"IIS Parser\",\"FactoryId\":\"ad7187b1-bd09-4bfe-a28b-3fd3de879009\",\"UserSetti" +
            "ngFileAssociations\":[],\"Status\":2},{\"FactoryName\":\"Json Log Parser\",\"FactoryId\":" +
            "\"d7146342-aeb2-4bd5-8710-7d1bf06ea5cf\",\"UserSettingFileAssociations\":[],\"Status\"" +
            ":1},{\"FactoryName\":\"Log4Net Parser\",\"FactoryId\":\"dbc17c75-5212-46e3-b98a-539e779" +
            "000e3\",\"UserSettingFileAssociations\":[],\"Status\":1},{\"FactoryName\":\"NLogs Parser" +
            "\",\"FactoryId\":\"33cbfa00-da3e-4f9f-b5a1-be978fd09d57\",\"UserSettingFileAssociation" +
            "s\":[],\"Status\":1},{\"FactoryName\":\"Plain Text Parser\",\"FactoryId\":\"11cbfa00-da2e-" +
            "2f9f-b5a1-be978fd09d57\",\"UserSettingFileAssociations\":[],\"Status\":2},{\"FactoryNa" +
            "me\":\"Regular Expression Parser\",\"FactoryId\":\"7da2570c-92aa-423f-bcd8-43bb877463f" +
            "6\",\"UserSettingFileAssociations\":[],\"Status\":2},{\"FactoryName\":\"Serilog Parser\"," +
            "\"FactoryId\":\"513a4393-425e-4054-92d4-6a816983e51f\",\"UserSettingFileAssociations\"" +
            ":[],\"Status\":1},{\"FactoryName\":\"Windows Event logs\",\"FactoryId\":\"3999db4c-0e22-4" +
            "795-92c1-61b05edb3f6c\",\"UserSettingFileAssociations\":[],\"Status\":1},{\"FactoryNam" +
            "e\":\"XML Text Parser\",\"FactoryId\":\"9652600e-1b14-4812-bcec-9a6194db9aea\",\"UserSet" +
            "tingFileAssociations\":[],\"Status\":1},{\"FactoryName\":\"Git History\",\"FactoryId\":\"b" +
            "842cc0f-ad83-48fb-8394-3189f9a75024\",\"UserSettingFileAssociations\":[],\"Status\":2" +
            "},{\"FactoryName\":\"GitHub\",\"FactoryId\":\"8064229a-2605-42fa-9e72-75444e4ab13f\",\"Us" +
            "erSettingFileAssociations\":[],\"Status\":2}]")]
        public string FactoriesSettings {
            get {
                return ((string)(this["FactoriesSettings"]));
            }
            set {
                this["FactoriesSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid LastOpenedDataProvider {
            get {
                return ((global::System.Guid)(this["LastOpenedDataProvider"]));
            }
            set {
                this["LastOpenedDataProvider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RememberLastOpenedDataProvider {
            get {
                return ((bool)(this["RememberLastOpenedDataProvider"]));
            }
            set {
                this["RememberLastOpenedDataProvider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreDefinedQueries {
            get {
                return ((string)(this["PreDefinedQueries"]));
            }
            set {
                this["PreDefinedQueries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RememberLastSearches {
            get {
                return ((bool)(this["RememberLastSearches"]));
            }
            set {
                this["RememberLastSearches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int NumberOfLastSearches {
            get {
                return ((int)(this["NumberOfLastSearches"]));
            }
            set {
                this["NumberOfLastSearches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSearchesInclude {
            get {
                return ((string)(this["LastSearchesInclude"]));
            }
            set {
                this["LastSearchesInclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSearchesExclude {
            get {
                return ((string)(this["LastSearchesExclude"]));
            }
            set {
                this["LastSearchesExclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[]")]
        public string AdditionalProbingLocations {
            get {
                return ((string)(this["AdditionalProbingLocations"]));
            }
            set {
                this["AdditionalProbingLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SingleInstance {
            get {
                return ((bool)(this["SingleInstance"]));
            }
            set {
                this["SingleInstance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dark")]
        public string AnalogyIcon {
            get {
                return ((string)(this["AnalogyIcon"]));
            }
            set {
                this["AnalogyIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy.MM.dd HH:mm:ss.ff")]
        public string DateTimePattern {
            get {
                return ((string)(this["DateTimePattern"]));
            }
            set {
                this["DateTimePattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2019-11-01")]
        public global::System.DateTime LastUpdate {
            get {
                return ((global::System.DateTime)(this["LastUpdate"]));
            }
            set {
                this["LastUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int UpdateMode {
            get {
                return ((int)(this["UpdateMode"]));
            }
            set {
                this["UpdateMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastVersionChecked {
            get {
                return ((string)(this["LastVersionChecked"]));
            }
            set {
                this["LastVersionChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizedToTrayBar {
            get {
                return ((bool)(this["MinimizedToTrayBar"]));
            }
            set {
                this["MinimizedToTrayBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RecentFoldersCount {
            get {
                return ((int)(this["RecentFoldersCount"]));
            }
            set {
                this["RecentFoldersCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentFolders {
            get {
                return ((string)(this["RecentFolders"]));
            }
            set {
                this["RecentFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckAdditionalInformation {
            get {
                return ((bool)(this["CheckAdditionalInformation"]));
            }
            set {
                this["CheckAdditionalInformation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AnalogyPosition {
            get {
                return ((string)(this["AnalogyPosition"]));
            }
            set {
                this["AnalogyPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableCompressedArchives {
            get {
                return ((bool)(this["EnableCompressedArchives"]));
            }
            set {
                this["EnableCompressedArchives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsBuiltInSearchPanelVisible {
            get {
                return ((bool)(this["IsBuiltInSearchPanelVisible"]));
            }
            set {
                this["IsBuiltInSearchPanelVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Search")]
        public string BuiltInSearchPanelMode {
            get {
                return ((string)(this["BuiltInSearchPanelMode"]));
            }
            set {
                this["BuiltInSearchPanelMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationSvgPaletteName {
            get {
                return ((string)(this["ApplicationSvgPaletteName"]));
            }
            set {
                this["ApplicationSvgPaletteName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Skin")]
        public string ApplicationStyle {
            get {
                return ((string)(this["ApplicationStyle"]));
            }
            set {
                this["ApplicationStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMessageDetails {
            get {
                return ((bool)(this["ShowMessageDetails"]));
            }
            set {
                this["ShowMessageDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcludeText {
            get {
                return ((string)(this["ExcludeText"]));
            }
            set {
                this["ExcludeText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Single\"")]
        public string LogLevelSelection {
            get {
                return ((string)(this["LogLevelSelection"]));
            }
            set {
                this["LogLevelSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWhatIsNewAtStartup {
            get {
                return ((bool)(this["ShowWhatIsNewAtStartup"]));
            }
            set {
                this["ShowWhatIsNewAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FontSettings {
            get {
                return ((string)(this["FontSettings"]));
            }
            set {
                this["FontSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RibbonStyle {
            get {
                return ((int)(this["RibbonStyle"]));
            }
            set {
                this["RibbonStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableFirstChanceException {
            get {
                return ((bool)(this["EnableFirstChanceException"]));
            }
            set {
                this["EnableFirstChanceException"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TrackActiveMessage {
            get {
                return ((bool)(this["TrackActiveMessage"]));
            }
            set {
                this["TrackActiveMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float RealTimeRefreshInterval {
            get {
                return ((float)(this["RealTimeRefreshInterval"]));
            }
            set {
                this["RealTimeRefreshInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilteringExclusion {
            get {
                return ((string)(this["FilteringExclusion"]));
            }
            set {
                this["FilteringExclusion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogsLayoutFileName {
            get {
                return ((string)(this["LogsLayoutFileName"]));
            }
            set {
                this["LogsLayoutFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCustomLogsLayout {
            get {
                return ((bool)(this["UseCustomLogsLayout"]));
            }
            set {
                this["UseCustomLogsLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewDetailedMessageWithHTML {
            get {
                return ((bool)(this["ViewDetailedMessageWithHTML"]));
            }
            set {
                this["ViewDetailedMessageWithHTML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PerUser")]
        public string SettingsMode {
            get {
                return ((string)(this["SettingsMode"]));
            }
            set {
                this["SettingsMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RibbonForm")]
        public string MainFormType {
            get {
                return ((string)(this["MainFormType"]));
            }
            set {
                this["MainFormType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultUserLogFolder {
            get {
                return ((string)(this["DefaultUserLogFolder"]));
            }
            set {
                this["DefaultUserLogFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TimeOffset {
            get {
                return ((double)(this["TimeOffset"]));
            }
            set {
                this["TimeOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string TimeOffsetType {
            get {
                return ((string)(this["TimeOffsetType"]));
            }
            set {
                this["TimeOffsetType"] = value;
            }
        }
    }
}
